spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/gambti
    username: root
    password: green502
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# mybatis config
mybatis:
  type-aliases-package: com.green.gambti
  mapper-locations: classpath:mapper/**/*.xml

# swagger
springdoc:
  swagger-ui:
    path: /swagger.html

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mariadb://${HOST}:${MARIADB_PORT}/${DATABASE_NAME}
    username: ${USER_NAME}
    password: ${PASSWORD}