spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${MARIA_HOST}:${MARIA_PORT}/${DATABASE_NAME}
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# swagger
springdoc:
  swagger-ui:
    path: /swagger.html

img:
  dir: http://gambti.ap-northeast-2.elasticbeanstalk.com/img

server:
  port: 5000